language: php

php:
  - 7.4
  - 8.0

before_install:
  - composer self-update

install:
  #- composer install --no-interaction --prefer-source
  - composer install --no-interaction --prefer-source --ignore-platform-reqs # --ignore-platform-reqs because of consistence/coding-standard

script:
  - composer phpcs
  - composer phpstan
  - composer tests

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
